# -------------------------------------------------------------------------
# This is the default spack repository configuration. It includes the
# builtin spack package repository.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/repos.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/repos.yaml
# -------------------------------------------------------------------------
repos:
  builtin:
    git: https://github.com/spack/spack-packages.git
    branch: releases/v2025.07
