#!/bin/bash

dt=$(date +"%Y%m%d%H%M")
TZ=UTC sacct --clusters=coeus.cluster --allusers \
    --parsable2 --noheader --allocations --duplicates \
    --format jobid,jobidraw,cluster,partition,qos,account,group,gid,user,uid,\
submit,eligible,start,end,elapsed,exitcode,state,nnodes,ncpus,reqcpus,reqmem,\
reqtres,alloctres,timelimit,nodelist,jobname \
    --starttime now-1hour > /cluster/xdmod/coeus${dt}.txt

# Example of specific time frame
#    --starttime 2025-03-30T00:00:00 --endtime 2025-03-30T23:59:59 >/tmp/slurm.log
