#!/bin/bash

date >> ingestor.log
ingestlog="ingestor_$(date +'%Y%m%d%H%M').log"

TZ=UTC
cd /orcacluster/xdmod
echo ">>> Run shredder <<<" | tee >> $ingestlog
./shred | tee >> $ingestlog
if [[ $? -ne 0 ]]; then
    echo "Shredder failed, check $ingestlog"
fi
echo ">>> Run ingestor <<<" | tee >> $ingestlog
/usr/bin/xdmod-ingestor >> $ingestlog
status=$?
if [[ $status -ne 0 ]]; then
    echo "Ingestor failed, check $ingestlog"
    exit $status
fi
mv -f $ingestlog logs
gzip logs/$ingestlog
