#!/bin/bash

TZ=UTC
cd /coeuscluster/xdmod
for src in coeus*.txt; do
    if [[ -s $src ]]; then
        /usr/bin/xdmod-shredder -r Coeus -f slurm -i $src
        mv $src "_$src"
	gzip "_$src"
    else
    	rm -f $src
    fi
done
cd /orcacluster/xdmod
for src in orca*.txt; do
    if [[ -s $src ]]; then
        /usr/bin/xdmod-shredder -r Orca -f slurm -i $src
        mv $src "_$src"
	gzip "_$src"
    else
    	rm -f $src
    fi
done
/usr/bin/xdmod-ingest
